[package]
name = "cosmwasm-vm-derive"
edition = "2021"
version.workspace = true
description = "Derive macros for cosmwasm-vm. For internal use only. No stability guarantees."

[lib]
proc-macro = true

[dependencies]
blake3 = "1.5"
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = { version = "2.0.77", features = ["extra-traits", "full"] }
