[package]
name = "cosmwasm-schema-derive"
version = "2.0.0"
authors = ["Tomasz Kurcz <tom@confio.gmbh>"]
edition = "2021"
description = "Derive macros for cosmwasm-schema"
repository = "https://github.com/CosmWasm/cosmwasm/tree/main/packages/schema"
license = "Apache-2.0"

[dependencies]
heck = "0.5.0"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["extra-traits", "full", "printing"] }

[lib]
proc-macro = true
