[package]
name = "cosmwasm-core"
version.workspace = true
edition = "2021"
description = "Components of cosmwasm-std that can be used in no_std environments"
repository = "https://github.com/CosmWasm/cosmwasm/tree/main/packages/core"
license = "Apache-2.0"
readme = "README.md"

[package.metadata.release]
release = false

[dependencies]
base64 = { version = "0.22.0", default-features = false, features = ["alloc"] }
bnum = "0.11.0"
crc32fast = { version = "1.4.0", optional = true, default-features = false }
derive_more = { version = "1.0.0-beta.6", default-features = false, features = ["display", "from"] }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
schemars = { version = "0.8.16", optional = true }
serde = { version = "1.0.197", default-features = false, features = ["derive"] }
serde-json-wasm = { version = "1.0.1", default-features = false }
static_assertions = "1.1.0"

[features]
std = ["dep:schemars"]
# Expose things that are usually gated behind `#[cfg(test)]` inside the `testing` module (do NOT use in production)
#
# Also this is semver exempt. Beware here be dragons.
testing = ["dep:crc32fast"]

[dev-dependencies]
# I love cyclic dependencies. They are good for your health.
cosmwasm-std = { path = "../std", version = "2.0.0" }
crc32fast = { version = "1.4.0", default-features = false }
