[package]
name = "cosmwasm-core"
version.workspace = true
edition = "2021"
description = "Components of cosmwasm-std that can be used in no_std environments"
repository = "https://github.com/CosmWasm/cosmwasm/tree/main/packages/core"
license = "Apache-2.0"
readme = "README.md"

[package.metadata.release]
release = false

[dependencies]
base64 = { version = "0.22.0", default-features = false, features = ["alloc"] }
bnum = "0.11.0"
cosmwasm-crypto = { version = "2.0.0", path = "../crypto" }
derive_more = { version = "1.0.0-beta.6", default-features = false, features = ["display", "from"] }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
schemars = { version = "0.8.16", optional = true }
serde = { version = "1.0.197", default-features = false, features = ["alloc", "derive"] }
sha2 = { version = "0.10.8", default-features = false }
static_assertions = "1.1.0"

[features]
std = ["dep:schemars"]

[dev-dependencies]
# Cyclic dependencies for doc tests..
cosmwasm-std = { path = "../std", version = "2.0.0" }
crc32fast = { version = "1.4.0", default-features = false }
hex-literal = "0.4.1"
serde_json = "1.0.114"
