[package]
name = "cosmwasm-vm-derive-impl"
edition = "2021"
version.workspace = true

[lib]
proc-macro = true

[dependencies]
blake3 = "1.5.4"
cargo-manifest = "0.15.2"
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = "2.0.77"
