[package]
name = "go-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schemars = "0.8.3"
cosmwasm-std = { path = "../std", version = "1.3.1" }
cosmwasm-schema = { path = "../schema", version = "1.3.1" }
anyhow = "1"
Inflector = "0.11.4"
