[package]
name = "go-gen"
authors = ["Christoph Otter <chris@confio.gmbh>"]
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { path = "../std", features = ["cosmwasm_2_0", "staking", "stargate"] }
cosmwasm-schema = { path = "../schema" }
anyhow = "1"
Inflector = "0.11.4"
indenter = "0.3.3"
schemars = { workspace = true }
